// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // Used by `prisma migrate` / `prisma db pull` — the direct (non-pooled)
  // connection, required on Vercel's serverless runtime (docs/PLAN.md §9.1).
  // PrismaClient at runtime uses the pooled DATABASE_URL via a driver adapter
  // instead — see src/lib/db.ts.
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});
